let logOffset=0,logHasMore=false,logPageSize=50;
function logIsoFrom(id,end=false){const v=$(id).value;if(!v)return null;return v+(end?'T23:59:59.999Z':'T00:00:00Z')}
function fillSelect(id,items,label){const el=$(id),value=el.value;el.innerHTML='<option value="all">'+label+'</option>'+items.map(x=>`<option value="${esc(x)}">${esc(x)}</option>`).join('');if([...el.options].some(o=>o.value===value))el.value=value}
async function loadLogs(offset=logOffset){
  if(!token)return;logOffset=Math.max(0,offset);const st=$('#logStatus'),list=$('#logList');st.className='status muted';st.textContent='Logs werden geladen…';
  try{const out=await rpc('get_admin_activity_log',{p_limit:logPageSize,p_offset:logOffset,p_alliance:$('#logAlliance').value||'all',p_category:$('#logCategory').value||'all',p_action:$('#logAction').value||'all',p_entity_type:$('#logEntity').value||'all',p_from:logIsoFrom('#logFrom'),p_to:logIsoFrom('#logTo',true),p_search:$('#logSearch').value.trim()||null});
    const rows=out?.rows||[];logHasMore=!!out?.has_more;fillSelect('#logAlliance',out?.alliances||[],'Alle Allianzen');fillSelect('#logAction',out?.actions||[],'Alle Aktionen');fillSelect('#logEntity',out?.entity_types||[],'Alle Objekte');
    st.textContent=rows.length+' Einträge auf dieser Seite';list.innerHTML=rows.length?rows.map(renderLogRow).join(''):'<div class="empty-state">Keine passenden Logeinträge.</div>';$('#logPrev').disabled=logOffset===0;$('#logNext').disabled=!logHasMore;$('#logPage').textContent='Seite '+(Math.floor(logOffset/logPageSize)+1);
  }catch(e){st.className='status err';st.textContent=e.message;list.innerHTML=''}
}
function renderLogRow(a){const details=a.details&&typeof a.details==='object'?a.details:{},summary=details.public&&typeof details.public==='object'?details.public:details,label=summary.player_name||summary.event_name||summary.login_email||summary.status||a.reason||'';return `<details class="log-item"><summary><span class="log-time">${esc(dt(a.created_at))}</span><div class="log-main"><b>${esc(a.action)}</b><small>${esc(a.alliance_code||'System')} · ${esc(a.entity_type||'–')}${label?' · '+esc(label):''}</small></div><span class="badge blue">Details</span></summary><div class="log-detail"><div class="detail-grid"><div class="detail-box"><b>Alliance</b>${esc(a.alliance_code||'–')}</div><div class="detail-box"><b>Action</b>${esc(a.action)}</div><div class="detail-box"><b>Entity</b>${esc(a.entity_type||'–')}</div><div class="detail-box"><b>Entity ID</b>${esc(a.entity_id||'–')}</div><div class="detail-box"><b>Actor</b>${esc(a.actor||'–')}</div><div class="detail-box"><b>Reason</b>${esc(a.reason||'–')}</div></div><pre class="json-box">${esc(JSON.stringify(details,null,2))}</pre></div></details>`}
function resetLogFilters(){['#logAlliance','#logCategory','#logAction','#logEntity'].forEach(id=>$(id).value='all');['#logFrom','#logTo','#logSearch'].forEach(id=>$(id).value='');loadLogs(0)}
