
(()=>{'use strict';
const DAY=86400000;
function sameDay(a,b){return a&&a.getFullYear()===b.getFullYear()&&a.getMonth()===b.getMonth()&&a.getDate()===b.getDate()}
function usageState(v){if(!v)return {label:'Noch nie aktiv',cls:'off'};const d=new Date(v),now=new Date();if(sameDay(d,now))return {label:'Heute aktiv',cls:'today'};if(now-d<=7*DAY)return {label:'Letzte 7 Tage',cls:'week'};return {label:'Länger nicht aktiv',cls:'off'}}
renderUsage=function(u){
 const now=new Date();
 const today=u.filter(x=>x.last_sign_in_at&&sameDay(new Date(x.last_sign_in_at),now)).length;
 const week=u.filter(x=>x.last_sign_in_at&&now-new Date(x.last_sign_in_at)<=7*DAY).length;
 const active=u.reduce((s,x)=>s+Number(x.active_violations||0),0);
 $('#kpis').innerHTML=`<div class="k"><b>${u.length}</b><span>Allianzen</span></div><div class="k"><b>${today}</b><span>heute aktiv</span></div><div class="k"><b>${week}</b><span>in den letzten 7 Tagen aktiv</span></div><div class="k"><b>${fmt(active)}</b><span>aktive Verstöße</span></div>`;
 $('#quick').innerHTML=u.map(x=>{const s=usageState(x.last_sign_in_at);return `<div class="q"><div class="qtop"><span class="qname">${esc(x.alliance_code)}</span><span class="qnum">${fmt(x.active_violations||0)}</span></div><div class="qmeta"><span class="dot ${s.cls}"></span>${s.label}<br>${x.last_sign_in_at?'Zuletzt aktiv '+dt(x.last_sign_in_at):'Noch keine Nutzung erkannt'}<br>${fmt(x.active_violations||0)} aktive Verstöße</div></div>`}).join('');
 $('#alist').innerHTML=u.map(x=>{const a=esc(x.alliance_code),s=usageState(x.last_sign_in_at);return `<div class="item"><div class="top"><div><b>${a}</b><div class="muted" style="font-size:12px">Zuletzt aktiv: ${dt(x.last_sign_in_at)} · ${fmt(x.active_violations||0)} aktive Verstöße</div></div><span class="usage-badge ${s.cls}">${s.label}</span></div><div class="pwd"><input id="p-${a}" type="password" placeholder="Neues Passwort (min. 10 Zeichen)"><div class="row"><button class="s genp" data-a="${a}">Generieren</button><button class="g cpp" data-a="${a}">Kopieren</button><button class="p setp" data-a="${a}">Setzen</button></div></div><div id="st-${a}" class="status muted"></div></div>`}).join('');
 document.querySelectorAll('.genp').forEach(b=>b.onclick=()=>{$('#p-'+b.dataset.a).value=rnd()});
 document.querySelectorAll('.cpp').forEach(b=>b.onclick=async()=>{$('#st-'+b.dataset.a).textContent=await cp($('#p-'+b.dataset.a).value)?'Kopiert.':'Kopieren nicht möglich.'});
 document.querySelectorAll('.setp').forEach(b=>b.onclick=()=>setPwd(b.dataset.a));
};
const st=document.createElement('style');st.textContent='.kpis{grid-template-columns:repeat(4,minmax(0,1fr))!important}.usage-badge{font-size:10px;padding:4px 7px;border-radius:999px;border:1px solid #315c78;white-space:nowrap}.usage-badge.today{color:#aaf0cb;border-color:#367b5a;background:rgba(109,224,168,.08)}.usage-badge.week{color:#ffe0a4;border-color:#8a6b32;background:rgba(244,194,92,.08)}.usage-badge.off{color:#9eb0c2;border-color:#435566}.dot.today{background:#6de0a8}.dot.week{background:#f4c25c}.dot.off{background:#6f8090}@media(max-width:650px){.kpis{grid-template-columns:1fr 1fr!important}}';document.head.appendChild(st);
})();


(()=>{'use strict';
if(window.__ADMIN_ACTIVITY_V1)return;window.__ADMIN_ACTIVITY_V1=true;
const app=document.querySelector('#app');
if(!app)return;
const sec=document.createElement('section');sec.className='card';sec.id='activityCard';
sec.innerHTML=`<div class="top"><div><h2>Activity Log</h2><div class="muted">Systemweite Änderungen, Imports und Löschungen</div></div><button id="activityReload" class="g">Aktualisieren</button></div><div class="row" style="margin-top:12px"><select id="activityAlliance"><option value="">Alle Allianzen</option><option>NRW</option><option>THM</option><option>NWO</option><option>CWR</option><option>PxR</option><option>NwO</option><option>ADMIN</option></select><select id="activityKind"><option value="">Alle Aktionen</option><option value="screen">ScreenRecording / Import</option><option value="delete">Löschungen</option><option value="player">Spieler</option><option value="violation">Verstöße</option></select></div><div id="activityStatus" class="status muted"></div><div id="activityList" class="activity-list"></div>`;
app.appendChild(sec);
function activityText(a){const d=a.details||{},act=String(a.action||'');if(act==='screen_recording_import')return `${d.event_name||'ScreenRecording'}${d.phase_name?' · '+d.phase_name:''}`;if(act==='performance_screen_import')return `${d.performance_type==='alliance_mobilization'?'Alliance Mobilization':'KvK Prep'} · ${d.imported??0} importiert`;if(act==='violation_deleted')return `Eintrag gelöscht${d.player_name?' · '+d.player_name:''}${d.event_name?' · '+d.event_name:''}`;if(act.includes('screen_import_occurrence'))return `${d.event_name||'ScreenRecording'} · ${act.endsWith('updated')?'aktualisiert':'erfasst'}`;return act.replaceAll('_',' ')}
function matchesKind(a,k){if(!k)return true;const s=(a.action+' '+a.entity_type).toLowerCase();if(k==='screen')return s.includes('screen')||s.includes('performance');if(k==='delete')return s.includes('delete');if(k==='player')return s.includes('player');if(k==='violation')return s.includes('violation');return true}
async function loadActivity(){const st=$('#activityStatus'),list=$('#activityList');if(!token||!list)return;st.className='status muted';st.textContent='Aktivitäten werden geladen…';try{const alliance=$('#activityAlliance')?.value||null;let rows=await rpc('get_activity_log',{p_limit:150,p_offset:0,p_alliance:alliance,p_action:null});rows=Array.isArray(rows)?rows:[];const kind=$('#activityKind')?.value||'';rows=rows.filter(x=>matchesKind(x,kind));st.textContent=rows.length?`${rows.length} Einträge`:'Keine Einträge für diesen Filter.';list.innerHTML=rows.map(a=>{const reason=a.reason?`<div class="activity-reason"><b>Löschgrund:</b> ${esc(a.reason)}</div>`:'';const detail=a.details||{};const stats=detail.stats&&typeof detail.stats==='object'?`<div class="muted" style="font-size:12px">${esc(JSON.stringify(detail.stats))}</div>`:'';return `<article class="activity-item"><div class="activity-head"><b>${esc(a.alliance_code||'System')}</b><span>${esc(dt(a.created_at))}</span></div><div>${esc(activityText(a))}</div>${reason}${stats}</article>`}).join('')}catch(e){st.className='status err';st.textContent=e.message;list.innerHTML=''}}
const baseLoadUsage=loadUsage;loadUsage=async function(){await baseLoadUsage();await loadActivity()};
$('#activityReload').onclick=loadActivity;$('#activityAlliance').onchange=loadActivity;$('#activityKind').onchange=loadActivity;
const st=document.createElement('style');st.textContent='.activity-list{display:grid;gap:8px;margin-top:10px}.activity-item{padding:11px;border:1px solid var(--b);border-radius:12px;background:rgba(255,255,255,.02)}.activity-head{display:flex;justify-content:space-between;gap:12px;margin-bottom:5px}.activity-head span{font-size:12px;color:var(--m)}.activity-reason{margin-top:7px;padding:7px 9px;border-left:3px solid var(--e);background:rgba(255,120,133,.06);font-size:12px}#activityCard select{min-width:160px}';document.head.appendChild(st);
})();
