'use strict';
const URL='https://bdzlgirowutasrsycjfj.supabase.co';
const KEY='sb_publishable_8i1ismeQtj9WM-xVN_Vm0w_Tj7AvVtL';
let token='',usageRows=[],accountRows=[],supportSummaryRows=[];
const $=s=>document.querySelector(s);
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const fmt=n=>Number(n||0).toLocaleString('de-DE');
const dt=v=>v?new Date(v).toLocaleString('de-DE',{dateStyle:'short',timeStyle:'short'}):'–';
const H=(json=true)=>({apikey:KEY,...(token?{Authorization:'Bearer '+token}:{}),...(json?{'Content-Type':'application/json'}:{})});
async function req(path,opt={}){let r;try{r=await fetch(URL+path,opt)}catch(e){throw new Error('Supabase nicht erreichbar: '+e.message)}let x=null;const ct=r.headers.get('content-type')||'';if(r.status!==204)x=ct.includes('json')?await r.json():await r.text();if(!r.ok)throw new Error((x&&typeof x==='object'&&(x.msg||x.message||x.error_description||x.error))||String(x||('HTTP '+r.status)));return x}
async function rpc(name,args={}){return req('/rest/v1/rpc/'+encodeURIComponent(name),{method:'POST',headers:H(),body:JSON.stringify(args)})}
function rnd(){const c='ABCDEFGHJKLMNPQRSTUVWXYZabcdefghijkmnopqrstuvwxyz23456789!@#$%_-',a=new Uint32Array(16);crypto.getRandomValues(a);return Array.from(a,n=>c[n%c.length]).join('')}
async function cp(v){try{await navigator.clipboard.writeText(v);return true}catch{return false}}
async function login(p){const x=await req('/auth/v1/token?grant_type=password',{method:'POST',headers:{apikey:KEY,'Content-Type':'application/json'},body:JSON.stringify({email:'admin@nap-tracker.invalid',password:p})});token=x.access_token||'';if(!token)throw new Error('Kein Zugriffstoken erhalten');const prof=await req('/rest/v1/profiles?select=alliance_code,is_admin&limit=1',{headers:H(false)});if(!prof?.[0]?.is_admin){token='';throw new Error('Dieser Zugang ist kein Admin-Konto.')}}
function usageState(v){if(!v)return{label:'Noch nie aktiv',cls:'gray'};const d=new Date(v),now=new Date(),days=(now-d)/86400000;if(d.toDateString()===now.toDateString())return{label:'Heute aktiv',cls:'green'};if(days<=7)return{label:'Letzte 7 Tage',cls:'gold'};return{label:'Länger inaktiv',cls:'gray'}}
async function loadDashboard(){const [u,a,t]=await Promise.all([rpc('get_admin_usage'),rpc('get_admin_accounts'),rpc('get_admin_support_tickets',{p_limit:250,p_offset:0,p_alliance:null,p_status:null,p_category:null})]);usageRows=Array.isArray(u)?u:[];accountRows=Array.isArray(a)?a:[];supportSummaryRows=Array.isArray(t)?t:[];renderDashboard();renderAccountOptions();if(typeof renderSupportSummary==='function')renderSupportSummary()}
function renderDashboard(){const now=new Date(),today=usageRows.filter(x=>x.last_sign_in_at&&new Date(x.last_sign_in_at).toDateString()===now.toDateString()).length,active=usageRows.reduce((s,x)=>s+Number(x.active_violations||0),0),openSupport=supportSummaryRows.filter(x=>x.status!=='resolved').length;$('#kpis').innerHTML=[['Allianzen',usageRows.length],['Heute aktiv',today],['Aktive Verstöße',fmt(active)],['Offene Tickets',openSupport]].map(([l,v])=>`<div class="kpi"><b>${esc(v)}</b><span>${esc(l)}</span></div>`).join('');$('#allianceOverview').innerHTML=usageRows.map(x=>{const st=usageState(x.last_sign_in_at);return `<div class="alliance-card"><div class="topline"><strong>${esc(x.alliance_code)}</strong><span class="badge ${st.cls}">${esc(st.label)}</span></div><div class="topline" style="margin-top:8px"><small>Aktive Verstöße</small><span class="violation-count">${fmt(x.active_violations)}</span></div><small>Letzter Login: ${esc(dt(x.last_sign_in_at))}</small></div>`}).join('');$('#supportOpenBadge').textContent=openSupport+' offen'}
function renderAccountOptions(){const sel=$('#accountSelect'),cur=sel.value;sel.innerHTML=accountRows.map(x=>`<option value="${esc(x.alliance_code)}">${esc(x.alliance_code)} · ${esc(x.login_email)}</option>`).join('');if(cur&&accountRows.some(x=>x.alliance_code===cur))sel.value=cur;renderAccountMeta()}
function selectedAccount(){return accountRows.find(x=>x.alliance_code===$('#accountSelect').value)||accountRows[0]||null}
function renderAccountMeta(){const a=selectedAccount(),host=$('#accountMeta'),btn=$('#toggleLock');if(!a){host.innerHTML='<span class="muted">Kein Account gefunden.</span>';btn.disabled=true;return}host.innerHTML=`<div class="meta-row"><span>Login</span><b>${esc(a.login_email)}</b></div><div class="meta-row"><span>Letzter Login</span><b>${esc(dt(a.last_sign_in_at))}</b></div><div class="meta-row"><span>Aktive Verstöße</span><b>${fmt(a.active_violations)}</b></div><div class="meta-row"><span>Status</span><span class="badge ${a.is_locked?'red':'green'}">${a.is_locked?'GESPERRT':'AKTIV'}</span></div>`;btn.disabled=false;btn.textContent=a.is_locked?'Account entsperren':'Account sperren';btn.className='btn '+(a.is_locked?'success':'danger')+' wide'}
async function setPassword(){const a=selectedAccount(),p=$('#accountPassword').value.trim(),st=$('#accountStatus');if(!a)return;if(p.length<10){st.className='status err';st.textContent='Mindestens 10 Zeichen.';return}if(!confirm('Passwort für '+a.alliance_code+' wirklich ändern?'))return;try{await rpc('admin_set_alliance_password',{p_alliance:a.alliance_code,p_password:p});st.className='status ok';st.textContent='Passwort gespeichert.'}catch(e){st.className='status err';st.textContent=e.message}}
async function toggleAccountLock(){const a=selectedAccount(),st=$('#accountStatus');if(!a)return;const next=!a.is_locked;if(!confirm((next?'Account sperren: ':'Account entsperren: ')+a.alliance_code+'?'))return;try{await rpc('admin_set_account_locked',{p_alliance:a.alliance_code,p_locked:next});st.className='status ok';st.textContent=next?'Account gesperrt.':'Account entsperrt.';await loadDashboard();if(typeof loadLogs==='function')loadLogs(0)}catch(e){st.className='status err';st.textContent=e.message}}
async function signSupportPath(path){const x=await req('/storage/v1/object/sign/support-evidence/'+path.split('/').map(encodeURIComponent).join('/'),{method:'POST',headers:H(),body:JSON.stringify({expiresIn:3600})});const s=x?.signedURL||x?.signedUrl||x?.signed_url;if(!s)return null;return s.startsWith('http')?s:URL+'/storage/v1'+s}
